site_name: GeoServer su Docker
site_author: by Totò
site_url: ""

# Copyright
copyright: <b>Ing. Salvatore Fiandaca</b> | 2025 | <a href="https://opendatasicilia.it/" target="_self" title="Chi Siamo" >About</a>

theme:
  name: material
  language: it

  features:
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.share
    - navigation.footer
    - toc.follow
    - content.action.edit
    - content.action.view
    - content.code.copy

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_url: https://github.com/pigreco/geoserver_su_docker
edit_uri: edit/main/docs/

## Page tree
nav:
  - Home: index.md
  - Abstract: abstract.md
  - Docker:
     - Intro: docker/docker.md
     - Installazione: docker/installazione.md
     - Download immagine: docker/immagine_geoserver.md
     - Montare volume: docker/montare_cartella_locale.md
  - GeoServer:
     - Introduzione: geoserver/introduzione.md
     - Configurazione: geoserver/configurazione.md
     - Creare un nuovo Workspace: geoserver/workspace.md
     - Creare un nuovo Store: geoserver/store.md
     - Creare un nuovo Layer: geoserver/layer.md
     - Creare un nuovo Style: geoserver/style.md
  - Link utili: link_utili.md


plugins:
- search
- social
- glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true


markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - tables
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - toc:
      permalink: true

## Social Media
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/totofiandaca
    - icon: fontawesome/brands/telegram
      link: https://t.me/pigrecoinfinito
    - icon: fontawesome/brands/creative-commons
      link: https://creativecommons.org/licenses/by-sa/4.0/deed.it
      name: Attribuzione - Condividi allo stesso modo 4.0 Internazionale (CC BY-SA 4.0)
